USE [master]
GO

/****** Object:  Database [Db_BookStore]    Script Date: 5/15/2023 3:34:27 PM ******/
CREATE DATABASE [Db_BookStore]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Db_BookStore', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\Db_BookStore.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Db_BookStore_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\Db_BookStore_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [Db_BookStore] SET COMPATIBILITY_LEVEL = 140
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Db_BookStore].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Db_BookStore] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Db_BookStore] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Db_BookStore] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Db_BookStore] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Db_BookStore] SET ARITHABORT OFF 
GO

ALTER DATABASE [Db_BookStore] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Db_BookStore] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Db_BookStore] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Db_BookStore] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Db_BookStore] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Db_BookStore] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Db_BookStore] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Db_BookStore] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Db_BookStore] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Db_BookStore] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Db_BookStore] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Db_BookStore] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Db_BookStore] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Db_BookStore] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Db_BookStore] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Db_BookStore] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Db_BookStore] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Db_BookStore] SET RECOVERY FULL 
GO

ALTER DATABASE [Db_BookStore] SET  MULTI_USER 
GO

ALTER DATABASE [Db_BookStore] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Db_BookStore] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Db_BookStore] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Db_BookStore] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Db_BookStore] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Db_BookStore] SET QUERY_STORE = OFF
GO

USE [Db_BookStore]
GO

ALTER DATABASE SCOPED CONFIGURATION SET IDENTITY_CACHE = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [Db_BookStore] SET  READ_WRITE 
GO


